### ISSUE TITLE
BottomNavigationView bugs

### ISSUE THREAD

**Issue by Jmc19** [kcozzone3/DigitalDoctorApp#98]
Currently cannot click on the padding section, review and fix. In addition, try to make icons larger.

**Comment by Jmc19** [comment]
I cannot change the icon size without creating a new section. Padding can wait for the future, hopefully fixed by the end of this sprint, but it won't be a clean fix

**Comment by kcozzone3** [comment]
So, to clarify, padding still needs to be fixed, which seems tricky. The padding size shouldn't affect mobile users too much, so I'll put this in backlog, to fix if there's nothing else. Not a high-priority bugfix.

**Comment by Jmc19** [comment]
This is unable to be fixed with our current API, and, since we do not wish to change API, this will have to stay in, unfortunately
